Repository jellyfin/jellyfin-plugin-bookshelf, pull requests merged in 2022-01, with the labels that each got.

#45 Refactor opf metadata reader for readability
  Jellyfin.Plugin.Bookshelf/Providers/BookProviderFromOpf.cs
  Jellyfin.Plugin.Bookshelf/Providers/Epub/EpubMetadataImageProvider.cs
  Jellyfin.Plugin.Bookshelf/Providers/Epub/EpubMetadataProvider.cs
  Jellyfin.Plugin.Bookshelf/Providers/OpfReader.cs
Labels: chore

#44 Use proper NormalziationForm
  Jellyfin.Plugin.Bookshelf/Providers/ComicVine/ComicVineMetadataProvider.cs
  Jellyfin.Plugin.Bookshelf/Providers/GoogleBooks/GoogleBooksProvider.cs
Labels: bug

#47 Read date and language information from opf
  Jellyfin.Plugin.Bookshelf/Providers/OpfReader.cs
Labels: enhancement
